export type Gate =
  // Keep this alphabetic please.
  | 'alt_share_icon'
  | 'debug_show_feedcontext'
  | 'debug_subscriptions'
  | 'disable_onboarding_policy_update_notice'
  | 'explore_show_suggested_feeds'
  | 'premium_subscriptions'
  | 'username_suggestions'
  | 'old_noteonboarding'
  | 'onboarding_add_video_feed'
  | 'note_threads_v2_unspecced'
  | 'remove_show_latest_button'
  | 'test_gate_1'
  | 'test_gate_2'
