# Sonet Docker Compose Environment Configuration
# This file contains environment variables for Docker Compose services
# Copy this to .env and modify as needed

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
postgres_db=sonet_dev
postgres_user=sonet
postgres_password=sonet_dev_password
NOTEGRES_MULTIPLE_DATABASES=user_service,note_service,media_service,follow_service,notification_service,messaging_service,timeline_service,search_service,analytics_service

# =============================================================================
# REDIS CONFIGURATION
# =============================================================================
REDIS_PASSWORD=
REDIS_DB=0

# =============================================================================
# JWT CONFIGURATION
# =============================================================================
JWT_SECRET=dev_jwt_secret_key_change_in_production
JWT_EXPIRES_IN=7d
JWT_REFRESH_EXPIRES_IN=30d

# =============================================================================
# SERVICE ENDPOINTS
# =============================================================================
USER_GRPC_ADDR=user-service:9090
NOTE_GRPC_ADDR=note-service:9090
TIMELINE_GRPC_ADDR=timeline-service:50051
MEDIA_GRPC_ADDR=media-service:9090
FOLLOW_GRPC_ADDR=follow-service:9090
SEARCH_GRPC_ADDR=search-service:9096
NOTIFICATION_GRPC_ADDR=notification-service:9097
MESSAGING_GRPC_ADDR=messaging-service:9095
ANALYTICS_GRPC_ADDR=analytics-service:9097

# =============================================================================
# SERVICE PORTS
# =============================================================================
USER_SERVICE_PORT=8081
USER_SERVICE_GRPC_PORT=9090
NOTE_SERVICE_PORT=8082
NOTE_SERVICE_GRPC_PORT=9091
MEDIA_SERVICE_PORT=8083
MEDIA_SERVICE_GRPC_PORT=9092
FOLLOW_SERVICE_PORT=8084
FOLLOW_SERVICE_GRPC_PORT=9093
NOTIFICATION_SERVICE_PORT=8085
NOTIFICATION_SERVICE_GRPC_PORT=9094
MESSAGING_SERVICE_PORT=8086
MESSAGING_SERVICE_GRPC_PORT=9095
TIMELINE_SERVICE_PORT=8087
TIMELINE_SERVICE_GRPC_PORT=50051
SEARCH_SERVICE_PORT=8088
SEARCH_SERVICE_GRPC_PORT=9096
ANALYTICS_SERVICE_PORT=8089
ANALYTICS_SERVICE_GRPC_PORT=9097

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOG_LEVEL=debug
LOG_FORMAT=json
LOG_DESTINATION=console

# =============================================================================
# FILE UPLOAD CONFIGURATION
# =============================================================================
MAX_FILE_SIZE=10485760
ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,video/mp4,video/webm

# =============================================================================
# RATE LIMITING CONFIGURATION
# =============================================================================
RATE_LIMIT_ENABLED=true
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# =============================================================================
# CDN CONFIGURATION
# =============================================================================
CDN_PROVIDER=local
CDN_BASE_URL=http://localhost:8080/cdn
CDN_REGION=us-east-1
CDN_ACCESS_KEY_ID=
CDN_SECRET_ACCESS_KEY=
CDN_BUCKET_NAME=sonet-media

# =============================================================================
# EXTERNAL SERVICES
# =============================================================================
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=noreply@sonet.app

FIREBASE_PROJECT_ID=
FIREBASE_PRIVATE_KEY_ID=
FIREBASE_PRIVATE_KEY=
FIREBASE_CLIENT_EMAIL=
FIREBASE_CLIENT_ID=

# =============================================================================
# MONITORING & ANALYTICS
# =============================================================================
SENTRY_DSN=
SENTRY_ORG=sonet
SENTRY_PROJECT=sonet-app
SENTRY_AUTH_TOKEN=

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
ENCRYPTION_ALGORITHM=AES-256-GCM
ENCRYPTION_KEY_SIZE=32
ENCRYPTION_IV_SIZE=12

MODERATION_API_KEY=
MODERATION_ENDPOINT=
MODERATION_THRESHOLD=0.8

# =============================================================================
# DEVELOPMENT CONFIGURATION
# =============================================================================
NODE_ENV=development
DEBUG=sonet:*
WATCH_MODE=true
AUTO_RESTART=true